### ISSUE TITLE
Please help: 502 gateway issue

### ISSUE THREAD

**Issue by hdeng88** [auth0/shiny-auth0#22]
Dear Auth0 team,

I am following the guide from https://auth0.com/blog/adding-authentication-to-shiny-server/ but encountered a 502 gateway error. 

The error messages are as follows if I manually run the service...:

/usr/bin/node /home/ubuntu/shiny-auth0/bin/www

Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.config (/home/ubuntu/shiny-auth0/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/home/ubuntu/shiny-auth0/app.js:12:8)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '.env'
}

/home/ubuntu/shiny-auth0/node_modules/passport-auth0/lib/index.js:36
      throw new Error('You must provide the ' + k + ' configuration value to use passport-auth0.');
      ^

Error: You must provide the domain configuration value to use passport-auth0.
    at /home/ubuntu/shiny-auth0/node_modules/passport-auth0/lib/index.js:36:13
    at Array.forEach (<anonymous>)
    at new Strategy (/home/ubuntu/shiny-auth0/node_modules/passport-auth0/lib/index.js:34:20)
    at Object.<anonymous> (/home/ubuntu/shiny-auth0/app.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)

Could you help with this matter? I noticed that someone was also experiencing the same problem after setup.

**Comment by hdeng88** [comment]
It turned out to a working dictionary issue for the .env file. This issue can be closed
